build: main.o get_name.o print_str.o
	gcc -o lab_1 main.o get_name.o print_str.o

get_name.o: get_name.c
	gcc -c -o get_name.o get_name.c

print_str.o: print_str.c
	gcc -c -o print_str.o print_str.c

main.o: main.c
	gcc -c -o main.o main.c